name: m_clearance_imigrasi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1
  shared_preferences: ^2.2.3
  cloud_functions: ^6.0.1
  lottie: ^3.3.1
  file_picker: ^10.3.2
  firebase_database: ^12.0.1
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  intl: ^0.20.2
  syncfusion_flutter_pdfviewer: ^31.1.17
  photo_view: ^0.15.0
  animations: ^2.0.11
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android: true
  ios: true
  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
