import 'dart:typed_data';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:http/http.dart' as http;
import '../models/report_model.dart';
import 'logging_service.dart';

class ReportService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FirebaseStorage _storage = FirebaseStorage.instance;

  // Get all reports for current officer
  Stream<List<ReportModel>> getReports() {
    final user = _auth.currentUser;
    if (user == null) return Stream.value([]);

    return _firestore
        .collection('reports')
        .where('createdBy', isEqualTo: user.uid)
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) =>
            snapshot.docs.map((doc) => ReportModel.fromFirestore(doc)).toList());
  }

  // Generate and save report
  Future<ReportModel?> generateReport(
      String type, Map<String, dynamic> stats) async {
    LoggingService().info('Generating report of type: $type with stats: $stats');
    try {
      final user = _auth.currentUser;
      if (user == null) {
        LoggingService().error('No authenticated user found');
        return null;
      }
      LoggingService().info('User found: ${user.uid}');

      final now = DateTime.now();
      final date = type == 'daily' ? now : DateTime(now.year, now.month, 1);
      final title = type == 'daily'
          ? 'Daily Report - ${date.toString().split(' ')[0]}'
          : 'Monthly Report - ${date.month}/${date.year}';
      LoggingService().info('Report title: $title');

      // Generate PDF
      LoggingService().info('Generating PDF...');
      final pdfBytes = await _generatePdf(title, stats, type, user.uid);
      LoggingService().info('PDF generated, size: ${pdfBytes.length}');

      // Upload to Firebase Storage
      LoggingService().info('Uploading PDF to storage...');
      final pdfUrl = await _uploadPdfToStorage(
          pdfBytes, '${type}_${date.millisecondsSinceEpoch}.pdf');
      LoggingService().info('PDF uploaded to: $pdfUrl');

      // Create a ReportModel instance
      final newReport = ReportModel(
        id: '', // Firestore will generate this
        type: type,
        date: date,
        createdBy: user.uid,
        stats: stats,
        pdfUrl: pdfUrl,
        createdAt: DateTime.now(),
        title: title,
      );
      LoggingService().info('Report model created');

      // Save to Firestore
      LoggingService().info('Saving report to Firestore...');
      final docRef = await _firestore
          .collection('reports')
          .add(newReport.toFirestore());
      LoggingService().info('Report saved with ID: ${docRef.id}');

      // Return the created report with its ID
      final createdReport = newReport.copyWith(id: docRef.id);

      LoggingService()
          .info('Report generated and saved successfully: ${docRef.id}');
      return createdReport;
    } catch (e, stackTrace) {
      LoggingService().error('Error generating report', e, stackTrace);
      return null;
    }
  }

  // Generate PDF with charts
  Future<Uint8List> _generatePdf(String title, Map<String, dynamic> stats,
      String type, String officerId) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Text(title,
                    style: pw.TextStyle(
                        fontSize: 24, fontWeight: pw.FontWeight.bold)),
              ),
              pw.SizedBox(height: 20),
              pw.Text('Generated on: ${DateTime.now().toString()}',
                  style: const pw.TextStyle(fontSize: 12)),
              pw.Text('Generated by: Officer $officerId',
                  style: const pw.TextStyle(fontSize: 12)),
              pw.SizedBox(height: 30),

              // Statistics Summary
              pw.Text('Statistics Summary', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              pw.Table(
                border: pw.TableBorder.all(),
                children: [
                  pw.TableRow(
                    children: [
                      pw.Text('Category', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                      pw.Text('Count', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                    ],
                  ),
                  pw.TableRow(
                    children: [
                      pw.Text('Pending Arrivals'),
                      pw.Text(stats['pendingArrival']?.toString() ?? '0'),
                    ],
                  ),
                  pw.TableRow(
                    children: [
                      pw.Text('Pending Departures'),
                      pw.Text(stats['pendingDeparture']?.toString() ?? '0'),
                    ],
                  ),
                  pw.TableRow(
                    children: [
                      pw.Text('Pending Accounts'),
                      pw.Text(stats['pendingAccounts']?.toString() ?? '0'),
                    ],
                  ),
                ],
              ),

              pw.SizedBox(height: 30),

              // Placeholder for chart (PDF charts are complex, would need custom implementation)
              pw.Text('Chart Visualization', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              pw.Text('Chart data will be displayed here in future updates', style: pw.TextStyle(fontSize: 10)),
            ],
          );
        },
      ),
    );

    return pdf.save();
  }


  // Upload PDF to Firebase Storage
  Future<String?> _uploadPdfToStorage(Uint8List pdfBytes, String fileName) async {
    try {
      final user = _auth.currentUser;
      if (user == null) return null;

      final storageRef = _storage.ref();
      final pdfRef = storageRef.child('reports/${user.uid}/$fileName');

      final uploadTask = pdfRef.putData(pdfBytes);
      final snapshot = await uploadTask.whenComplete(() => null);

      if (snapshot.state == TaskState.success) {
        final downloadUrl = await pdfRef.getDownloadURL();
        LoggingService().info('PDF uploaded successfully: $downloadUrl');
        return downloadUrl;
      } else {
        LoggingService().error('PDF upload failed');
        return null;
      }
    } catch (e) {
      LoggingService().error('Error uploading PDF', e);
      return null;
    }
  }

  // Download and share PDF
  Future<void> downloadReport(String pdfUrl, String fileName) async {
    try {
      await Printing.sharePdf(bytes: await _downloadPdfBytes(pdfUrl), filename: fileName);
    } catch (e) {
      LoggingService().error('Error downloading report', e);
    }
  }

  // Get PDF bytes from URL
  Future<Uint8List> _downloadPdfBytes(String url) async {
    final response = await http.get(Uri.parse(url));
    if (response.statusCode == 200) {
      return Uint8List.fromList(response.bodyBytes);
    } else {
      throw Exception('Failed to download PDF');
    }
  }

  // Delete report
  Future<bool> deleteReport(String reportId) async {
    try {
      final user = _auth.currentUser;
      if (user == null) return false;

      // Get report to check ownership and get PDF URL
      final doc = await _firestore.collection('reports').doc(reportId).get();
      if (!doc.exists) return false;

      final report = ReportModel.fromFirestore(doc);
      if (report.createdBy != user.uid) return false;

      // Delete PDF from storage if exists
      if (report.pdfUrl != null) {
        try {
          final pdfRef = _storage.refFromURL(report.pdfUrl!);
          await pdfRef.delete();
        } catch (e) {
          LoggingService().warning('Error deleting PDF from storage', e);
        }
      }

      // Delete from Firestore
      await _firestore.collection('reports').doc(reportId).delete();

      LoggingService().info('Report deleted successfully: $reportId');
      return true;
    } catch (e) {
      LoggingService().error('Error deleting report', e);
      return false;
    }
  }

  // Get report statistics
  Future<Map<String, int>> getReportStats() async {
    try {
      final user = _auth.currentUser;
      if (user == null) return {};

      final snapshot = await _firestore
          .collection('reports')
          .where('createdBy', isEqualTo: user.uid)
          .get();

      final stats = <String, int>{
        'total': snapshot.docs.length,
        'daily': 0,
        'monthly': 0,
      };

      for (final doc in snapshot.docs) {
        final report = ReportModel.fromFirestore(doc);
        if (report.type == 'daily') {
          stats['daily'] = (stats['daily'] ?? 0) + 1;
        } else if (report.type == 'monthly') {
          stats['monthly'] = (stats['monthly'] ?? 0) + 1;
        }
      }

      return stats;
    } catch (e) {
      LoggingService().error('Error getting report stats', e);
      return {};
    }
  }
}