// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz3J__EQv-UO6c5JusEReMvPwFfyl0LVg',
    appId: '1:672708613887:web:8c213f12350d73a1185eca',
    messagingSenderId: '672708613887',
    projectId: 'm-clearance-imigrasi-sampit',
    authDomain: 'm-clearance-imigrasi-sampit.firebaseapp.com',
    databaseURL:
        'https://m-clearance-imigrasi-sampit.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'm-clearance-imigrasi-sampit.firebasestorage.app',
    measurementId: 'G-RFXT7G9BRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKya9rhy6YGV7FKEpdfQqNn87dSkbPaXo',
    appId: '1:672708613887:android:8a7810cc54101c44185eca',
    messagingSenderId: '672708613887',
    projectId: 'm-clearance-imigrasi-sampit',
    databaseURL:
        'https://m-clearance-imigrasi-sampit.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'm-clearance-imigrasi-sampit.firebasestorage.app',
  );
}
