import 'package:flutter/material.dart';

/// AppStrings Class
///
/// Kelas ini berfungsi sebagai pusat untuk semua string (teks) dalam aplikasi.
/// Dengan pendekatan ini, kita memisahkan konten teks dari kode UI, yang sangat
/// penting untuk kemudahan maintenance dan proses internasionalisasi (i18n).
class AppStrings {
  /// Map privat yang menyimpan semua terjemahan.
  /// Strukturnya adalah: Bahasa -> NamaLayar -> KunciString -> Teks
  static final Map<String, Map<String, Map<String, String>>> _localizedStrings = {
    'EN': {
      //region Auth Screens
      'login': {
        'welcome': 'Welcome!',
        'email': 'Email Address',
        'email_hint': 'name@email.com',
        'email_req': 'Email is required',
        'email_invalid': 'Invalid email format',
        'password': 'Password',
        'password_hint': 'Enter your password',
        'password_req': 'Password is required',
        'forgot_password': 'Forgot password?',
        'login_button': 'Login',
        'not_a_member': 'Not a member?  ',
        'register_now': 'Register now',
        'invalid_credentials': 'Invalid username or password.',
        'account_pending': 'Your account is pending verification.',
        'account_rejected': 'Your account registration was rejected.',
        'logging_in': 'Logging in...',
      },
      'register': {
        'sign_up': 'Sign up',
        'create_account_subtitle': 'Create an account to get started',
        'corporate_name': 'Corporate Name',
        'corporate_name_hint': 'Enter your corporate name',
        'corporate_name_req': 'Corporate Name is required',
        'username': 'Username',
        'username_hint': 'Enter your username',
        'username_req': 'Username is required',
        'registration_failed': 'Registration failed. Please try again.',
        'registration_error': 'An unexpected error occurred during registration.',
        'email': 'Email Address',
        'email_hint': 'name@email.com',
        'email_req': 'Email is required',
        'email_invalid': 'Invalid email format',
        'password': 'Password',
        'password_hint': 'Create a password',
        'password_req': 'Password is required',
        'password_length': 'Password must be at least 6 characters',
        'confirm_password': 'Confirm Password',
        'confirm_password_hint': 'Confirm password',
        'confirm_password_req': 'Please confirm your password',
        'password_mismatch': 'Passwords do not match',
        'terms_agree': "I've read and agree with the ",
        'terms_and_conditions': 'Terms and Conditions',
        'and': ' and the ',
        'privacy_policy': 'Privacy Policy',
        'terms_req': 'You must agree to the Terms & Conditions and Privacy Policy.',
        'continue': 'Continue',
        'already_have_account': 'Already have an account? ',
        'login': 'Login',
      },
      'confirmation': {
        'title': 'Email Verification',
        'header': 'Enter confirmation code',
        'subtitle': 'A 4-digit code was sent to\n',
        'code_invalid': 'Confirmation code must be 4 digits.',
        'resend_code': 'Resend code',
        'resend_success': 'A new code has been sent.',
        'continue': 'Continue',
      },
      'uploadDocuments': {
        'title': 'Submission',
        'last_step': 'Last Step',
        'complete_req': 'Complete the Requirements',
        'nib_title': 'Business Identification Number',
        'nib_subtitle': 'Only accept .pdf',
        'ktp_title': 'Identity Card',
        'ktp_subtitle': 'Only accept .jpg .pdf',
        'submit': 'Submit',
        'upload_success': 'uploaded successfully (simulation).',
        'upload_all_docs': 'Please upload both documents.',
        'change': 'Change',
        'upload': 'Upload',
      },
      'registrationPending': {
        'title': 'Waiting for Verification',
        'message': 'You have successfully registered, please wait for verification. Check your email regularly.',
        'done_button': 'Done',
      },
      'forgotPassword': {
        'title': 'Forgot Password',
        'instruction': 'Enter your account email to receive a password recovery link.',
        'email_label': 'Email Address',
        'send_link_button': 'Send Reset Link',
        'success_dialog_title': 'Success',
        'success_dialog_content': 'A link to reset your password has been sent to the email:\n',
        'ok_button': 'OK',
        'invalid_email_message': 'Please enter a valid email address.',
      },
      'changePassword': {
        'title': 'Change Password',
        'instruction': 'For security, please enter your old password and create a new one.',
        'current_password': 'Current Password',
        'current_password_empty': 'Current password cannot be empty',
        'new_password': 'New Password',
        'new_password_empty': 'New password cannot be empty',
        'password_length': 'Password must be at least 6 characters',
        'confirm_new_password': 'Confirm New Password',
        'confirm_password_empty': 'Please confirm your new password',
        'passwords_do_not_match': 'Passwords do not match',
        'save_new_password': 'Save New Password',
        'password_updated': 'Password updated successfully!',
      },
      //endregion

      //region User Screens
      'userHome': {
        'home': 'Home',
        'history': 'History',
        'settings': 'Settings',
        'welcome': 'Welcome,',
        'last_transactions': 'Last Transactions',
        'no_transactions': 'No recent transactions yet.',
        'arrival': 'Arrival',
        'departure': 'Departure',
        'last_port': 'Last Port',
        'next_port': 'Next Port',
        'notifications': 'Notifications',
        'loading_user': 'Loading user data...',
      },
      'userHistory': {
        'history': 'History',
        'arrival': 'Arrival',
        'departure': 'Departure',
        'all': 'All',
        'empty_title': 'Nothing here. For now.',
        'empty_subtitle': "This is where you'll find your\nfinished application.",
        'waiting': 'WAITING FOR VERIFICATION',
        'revision': 'REQUIRES FIXING',
        'approved': 'ACCEPTED',
        'declined': 'DECLINED',
        'arrival_detail': 'Arrival Detail',
        'departure_detail': 'Departure Detail',
        'about': 'About',
        'last_port': 'Last Port',
        'next_port': 'Next Port',
        'crewlist': 'Crewlist',
        'agent': 'Agent',
        'note_by_officer': 'Note By Officer',
        'need_fix': 'Need Fix',
        'no_notes': 'No notes.',
        'fix_button': 'Fix',
        'done_button': 'Done',
        'reports_button': 'See Reports',
      },
      'userProfile': {
        'profile': 'Profile',
        'settings': 'Settings',
        'notifications': 'Notifications',
        'language': 'Language',
        'edit_profile': 'Edit Profile',
        'select_language': 'Select Language',
        'privacy_security': 'Privacy & Security',
        'change_password': 'Change Password',
        'logout': 'Logout',
        'logout_confirm_title': 'Logout',
        'logout_confirm_body': 'Are you sure you want to logout?',
        'cancel': 'Cancel',
      },
      'languageSelection': {
        'title': 'Select Language',
      },
      'editAgentProfile': {
        'title': 'Edit Agent Profile',
        'pick_image_source': 'Select Image Source',
        'gallery': 'Gallery',
        'camera': 'Camera',
        'change_profile_photo': 'Change Profile Photo',
        'full_name': 'Full Name',
        'full_name_empty': 'Name cannot be empty',
        'email_address': 'Email Address',
        'email_empty': 'Email cannot be empty',
        'email_invalid': 'Invalid email format',
        'save_changes': 'Save Changes',
        'profile_updated': 'Profile updated successfully!',
      },
      'clearanceForm': {
        'arrival_title': 'Arrival Details',
        'departure_title': 'Departure Details',
        'step1': 'Details',
        'step2': 'Documents',
        'step3': 'Submit',
        'form_instruction': 'Please fill the information before proceeding',
        'ship_name': 'Ship Name',
        'ship_name_hint': 'Ex: KM. Bahari Indah',
        'flag': 'Flag',
        'select_flag': 'Select ship flag',
        'location': 'Location',
        'select_location': 'Select location',
        'last_port': 'Last Port',
        'next_port': 'Next Port',
        'eta': 'ETA (Arrival Date)',
        'etd': 'ETD (Departure Date)',
        'select_date': 'Select Date',
        'wni_crew': 'WNI Crew',
        'wna_crew': 'WNA Crew',
        'required_field': 'This field is required',
        'next': 'Next',
        'back': 'Back',
        'upload_instruction': 'Please upload the required documents',
        'port_clearance': 'Port Clearance',
        'port_clearance_subtitle': 'Upload Port Clearance from previous port',
        'crew_list': 'Crew List',
        'crew_list_subtitle': 'Upload valid crew list document',
        'notification_letter': 'Notification Letter',
        'notification_letter_subtitle': 'Upload notification letter',
        'choose_file': 'Choose File',
        'file_uploaded': 'uploaded successfully',
        'edit': 'Edit',
        'upload_all_docs': 'Please upload all required documents.',
        'review_confirm': 'Review & Confirm',
        'vessel_details': 'Vessel Details',
        'crew_count': 'Crew Count',
        'required_docs': 'Required Documents',
        'not_uploaded': 'Not uploaded',
        'submit_application': 'Submit Application',
        'submit_dialog_title': 'Submit',
        'submit_dialog_content': 'Are you sure your application data is correct? Send to Proceed. We will review your application immediately.',
        'cancel': 'Cancel',
        'send': 'Send',
        'gallery': 'Choose from Gallery',
        'camera': 'Take a Picture',
        'file_picker': 'Choose from Files',
        'permission_required': 'Permission Required',
        'camera_permission_message': 'Camera permission is required to take photos. Please enable it in app settings.',
        'storage_permission_message': 'Storage permission is required to access photos. Please enable it in app settings.',
        'open_settings': 'Open Settings',
        'arrival_form': 'Arrival Clearance Form',
        'departure_form': 'Departure Clearance Form',
        'saving': 'Submitting...',
        'success_title': 'Application Submitted',
        'success_message': 'Your application has been submitted successfully',
        'error_title': 'Submission Failed',
        'error_message': 'Failed to submit application. Please try again.',
        'ok': 'OK',
        'invalid_number': 'Please enter a valid number',
        'select_file_failed': 'Failed to select file.',
      },
      'submissionSent': {
        'title': 'Verifying Documents',
        'message': 'Your submission is being processed. The status will be updated on the history page after verification by the officer.',
        'thank_you': 'Thank you for your submission!',
        'submission_received': 'Your application has been received and is being processed.',
        'tracking_info': 'You can track the status of your application in the History section.',
        'back_to_home': 'Back to Home',
        'view_history': 'View History',
      },
      'submissionWaiting': {
        'submission_received': 'Application Received',
        'processing': 'We are processing your application',
        'review_time': 'Our team will review your application within 1-2 business days.',
        'notification_info': 'You will receive a notification once your application is reviewed.',
        'check_status': 'Check Status',
        'back_to_home': 'Back to Home',
        'estimated_time': 'Estimated processing time: 1-2 business days',
      },
      'clearanceResult': {
        'title': 'Clearance Result',
        'print_simulation': 'Printing document... (simulation)',
        'share_simulation': 'Sharing document... (simulation)',
        'spb_title': 'Sailing Approval Letter',
        'immigration_office': 'Immigration Office Class II TPI Sampit',
        'approved_status': 'APPROVED',
        'approved_subtitle_arrival': 'The arrival clearance application has been approved.',
        'approved_subtitle_departure': 'The departure clearance application has been approved.',
        'ship_details': 'Ship Details',
        'ship_name': 'Ship Name',
        'flag': 'Flag',
        'agent': 'Agent',
        'voyage_details': 'Voyage Details',
        'last_port': 'Last Port',
        'next_port': 'Next Port',
        'eta': 'Arrival Date (ETA)',
        'etd': 'Departure Date (ETD)',
        'wni_crew': 'WNI Crew',
        'wna_crew': 'WNA Crew',
        'approved_by': 'Approved by Immigration Officer:',
        'officer_name': 'Officer Name',
        'approval_date': 'On Date:',
        'close_button': 'Close',
      },
      'userNotifications': {
        'title': 'Notification',
        'empty_title': 'Nothing here. For now.',
        'empty_subtitle': "This is where you'll find what is\ngoing on",
      },
      'notificationSettings': {
        'title': 'Notification Settings',
        'mute_notifications': 'Mute Notifications',
        'toggle_sound': 'Notification Sound',
        'view_notifications': 'View Notifications',
      },
      //endregion

      //region Officer Screens
      'adminHome': {
        'home': 'Home',
        'report': 'Report',
        'settings': 'Settings',
        'welcome': 'Welcome,',
        'officer': 'Officer',
        'immigration_office': 'Immigration Office Class II Sampit',
        'arrival_verification': 'Arrival Verification',
        'departure_verification': 'Departure Verification',
        'account_verification': 'Account Verification',
        'agent_submissions': 'Agent Submissions Check',
        'agent_registrations': 'Agent Registrations Check',
        'email_configuration': 'Email Configuration',
        'manage_email_settings': 'Manage email settings',
      },
      'adminProfile': {
        'settings': 'Settings',
        'notifications': 'Notifications',
        'language': 'Language',
        'english': 'English',
        'indonesian': 'Indonesia',
        'privacy_security': 'Privacy & Security',
        'change_password': 'Change Password',
        'logout': 'Logout',
        'page_not_available': 'page is not yet available.',
        'logout_confirm_title': 'Logout',
        'logout_confirm_body': 'Are you sure you want to logout?',
        'cancel': 'Cancel',
      },
      'verificationList': {
        'arrival_title': 'Arrival Verification',
        'departure_title': 'Departure Verification',
        'reviewed': 'Reviewed',
        'waiting': 'Waiting',
        'all': 'All',
        'no_data': 'No data for this filter.',
        'vessel_name': 'Vessel Name:',
        'verified': 'VERIFIED',
        'reviewed_decline': 'REVIEWED - DECLINE',
        'reviewed_fixing': 'REVIEWED - REQUIRE FIXING',
        'review_submission': 'REVIEW SUBMISSION',
      },
      'accountVerificationList': {
        'title': 'Account Verification',
        'reviewed': 'Reviewed',
        'waiting': 'Waiting',
        'all': 'All',
        'no_data': 'No data for this filter.',
        'agent_name': 'Agent Name:',
        'verified': 'VERIFIED',
        'reviewed_rejected': 'REVIEWED - REJECTED',
        'review_submission': 'REVIEW SUBMISSION',
      },
      'accountDetail': {
        'viewing_doc': 'Viewing Document:',
        'simulation_text': 'This is a simulation of viewing the file:\n',
        'close': 'Close',
        'user_details': 'User Details',
        'full_name': 'Full Name',
        'username': 'Username',
        'email': 'Email',
        'registration_docs': 'Registration Documents',
        'view_nib': 'View NIB File',
        'view_ktp': 'View KTP File',
        'reject': 'Reject',
        'verify_account': 'Verify Account',
        'rejected_message': 'Account rejected.',
        'verified_message': 'Account successfully verified.',
      },
      'submissionDetail': {
        'title': 'Verification Details',
        'submission_info': 'Submission Information',
        'ship_name': 'Ship Name',
        'flag': 'Flag',
        'agent_name': 'Agent Name',
        'location': 'Location',
        'port': 'Port',
        'arrival_date': 'Arrival Date',
        'departure_date': 'Departure Date',
        'wni_crew': 'WNI Crew',
        'wna_crew': 'WNA Crew',
        'doc_verification': 'Document Verification',
        'port_clearance': 'Port Clearance',
        'crew_list': 'Crew List',
        'notification_letter': 'Notification Letter',
        'action': 'Action',
        'reject_submission': 'Reject Submission',
        'finish_verification': 'Finish Verification',
        'check_all_docs_warning': 'Please check all documents first.',
        'revision_sent_success': 'Revision status has been sent to the agent.',
        'approved_success': 'Submission has been approved.',
        'rejected_success': 'Submission has been rejected.',
        'revision_notes_title': 'Revision Notes for',
        'revision_notes_hint': 'Enter revision notes...',
        'cancel': 'Cancel',
        'save': 'Save',
        'doc_preview_title': 'Document Preview',
        'doc_preview_content': 'This is a simulation preview for the document:\n',
        'close': 'Close',
        'status_pending': 'Pending',
        'status_approved': 'Approved',
        'status_revision': 'Revision',
        'view': 'View',
        'notes': 'Notes',
      },
      'officerReport': {
        'title': 'Officer Report',
        'daily_monthly_report': 'Daily & Monthly Report',
        'today': 'Today',
        'this_month': 'This Month',
        'arrival': 'Arrival',
        'departure': 'Departure',
        'registration': 'Registration',
        'daily_report': 'Daily Report',
        'create_new_report': 'Create New Report',
        'generating_pdf': 'Generating .pdf',
        'pdf_generation_simulation': 'Creating PDF report... (simulation)',
        'report_history': 'Report History',
        'created_by': 'Created by',
        'see_details': 'SEE DETAILS',
        'daily_report_type': 'Daily Report',
        'monthly_report_type': 'Monthly Report',
      },
      'editOfficerProfile': {
        'title': 'Edit Profile',
        'pick_image_source': 'Select Image Source',
        'gallery': 'Gallery',
        'camera': 'Camera',
        'change_profile_photo': 'Change Profile Photo',
        'full_name': 'Full Name',
        'full_name_empty': 'Name cannot be empty',
        'email_address': 'Email Address',
        'email_empty': 'Email cannot be empty',
        'email_invalid': 'Invalid email format',
        'save_changes': 'Save Changes',
        'profile_updated': 'Profile updated successfully!',
      },
      'officerNotifications': {
        'title': 'Notifications',
        'mark_all_read_tooltip': 'Mark all as read',
        'mark_all_read_message': 'All notifications marked as read (simulation).',
        'empty_title': 'Nothing here. For now.',
        'empty_subtitle': "This is where you'll find what is\ngoing on",
        'new_agent_reg_title': 'New Agent Registration',
        'new_agent_reg_body': 'PT. Bintang Samudera has submitted a registration. Please review the documents.',
        'submission_needs_review_title': 'Submission Needs Review',
        'submission_needs_review_body': 'KM. Egon has submitted an arrival application that needs your review.',
        'system_notice_title': 'System Notice',
        'system_notice_body': 'A scheduled system update will occur tonight at 02:00 WIB.',
      },
      // Remove duplicate/minimal re-definitions that overrode full maps
      //endregion
    },
    'ID': {
      //region Auth Screens
      'login': {
        'welcome': 'Selamat Datang!',
        'email': 'Alamat Email',
        'email_hint': 'nama@email.com',
        'email_req': 'Email harus diisi',
        'email_invalid': 'Format email tidak valid',
        'password': 'Kata Sandi',
        'password_hint': 'Masukkan kata sandi Anda',
        'password_req': 'Kata sandi harus diisi',
        'forgot_password': 'Lupa kata sandi?',
        'login_button': 'Masuk',
        'not_a_member': 'Bukan anggota?  ',
        'register_now': 'Daftar sekarang',
        'invalid_credentials': 'Nama pengguna atau kata sandi salah.',
        'account_pending': 'Akun Anda sedang menunggu verifikasi.',
        'account_rejected': 'Pendaftaran akun Anda ditolak.',
        'logging_in': 'Masuk...',
      },
      'register': {
        'sign_up': 'Daftar',
        'create_account_subtitle': 'Buat akun untuk memulai',
        'corporate_name': 'Nama Perusahaan',
        'corporate_name_hint': 'Masukkan nama perusahaan Anda',
        'corporate_name_req': 'Nama Perusahaan harus diisi',
        'username': 'Nama Pengguna',
        'username_hint': 'Masukkan nama pengguna Anda',
        'username_req': 'Nama Pengguna harus diisi',
        'registration_failed': 'Pendaftaran gagal. Silakan coba lagi.',
        'registration_error': 'Terjadi kesalahan tak terduga saat pendaftaran.',
        'email': 'Alamat Email',
        'email_hint': 'nama@email.com',
        'email_req': 'Email harus diisi',
        'email_invalid': 'Format email tidak valid',
        'password': 'Kata Sandi',
        'password_hint': 'Buat kata sandi',
        'password_req': 'Kata Sandi harus diisi',
        'password_length': 'Kata Sandi minimal 6 karakter',
        'confirm_password': 'Konfirmasi Kata Sandi',
        'confirm_password_hint': 'Konfirmasi kata sandi',
        'confirm_password_req': 'Mohon konfirmasi kata sandi Anda',
        'password_mismatch': 'Kata sandi tidak cocok',
        'terms_agree': "Saya telah membaca dan setuju dengan ",
        'terms_and_conditions': 'Syarat & Ketentuan',
        'and': ' dan ',
        'privacy_policy': 'Kebijakan Privasi',
        'terms_req': 'Anda harus menyetujui Syarat & Ketentuan serta Kebijakan Privasi.',
        'continue': 'Lanjutkan',
        'already_have_account': 'Sudah punya akun? ',
        'login': 'Masuk',
      },
      'confirmation': {
        'title': 'Verifikasi Email',
        'header': 'Masukkan kode konfirmasi',
        'subtitle': 'Kode 4 digit telah dikirim ke\n',
        'code_invalid': 'Kode konfirmasi harus 4 digit.',
        'resend_code': 'Kirim ulang kode',
        'resend_success': 'Kode baru telah dikirim.',
        'continue': 'Lanjutkan',
      },
      'uploadDocuments': {
        'title': 'Pengajuan',
        'last_step': 'Langkah Terakhir',
        'complete_req': 'Lengkapi Persyaratan',
        'nib_title': 'Nomor Induk Berusaha',
        'nib_subtitle': 'Hanya menerima .pdf',
        'ktp_title': 'Kartu Tanda Penduduk',
        'ktp_subtitle': 'Hanya menerima .jpg .pdf',
        'submit': 'Kirim',
        'upload_success': 'berhasil diunggah (simulasi).',
        'upload_all_docs': 'Mohon unggah kedua dokumen.',
        'change': 'Ganti',
        'upload': 'Unggah',
      },
      'registrationPending': {
        'title': 'Menunggu Verifikasi',
        'message': 'Anda telah berhasil mendaftar, mohon tunggu verifikasi. Periksa email Anda secara berkala.',
        'done_button': 'Selesai',
      },
      'forgotPassword': {
        'title': 'Lupa Kata Sandi',
        'instruction': 'Masukkan email akun Anda untuk menerima link pemulihan kata sandi.',
        'email_label': 'Alamat Email',
        'send_link_button': 'Kirim Link Reset',
        'success_dialog_title': 'Berhasil',
        'success_dialog_content': 'Link untuk mereset kata sandi telah dikirim ke email:\n',
        'ok_button': 'OK',
        'invalid_email_message': 'Mohon masukkan alamat email yang valid.',
      },
      'changePassword': {
        'title': 'Ubah Password',
        'instruction': 'Untuk keamanan, silakan masukkan password lama Anda dan buat password baru.',
        'current_password': 'Password Saat Ini',
        'current_password_empty': 'Password saat ini tidak boleh kosong',
        'new_password': 'Password Baru',
        'new_password_empty': 'Password baru tidak boleh kosong',
        'password_length': 'Password minimal harus 6 karakter',
        'confirm_new_password': 'Konfirmasi Password Baru',
        'confirm_password_empty': 'Mohon konfirmasi password baru Anda',
        'passwords_do_not_match': 'Password tidak cocok',
        'save_new_password': 'Simpan Password Baru',
        'password_updated': 'Password berhasil diperbarui!',
      },
      //endregion

      //region User Screens
      'userHome': {
        'home': 'Beranda',
        'history': 'Riwayat',
        'settings': 'Pengaturan',
        'welcome': 'Selamat Datang,',
        'last_transactions': 'Transaksi Terakhir',
        'no_transactions': 'Belum ada transaksi terakhir.',
        'arrival': 'Kedatangan',
        'departure': 'Keberangkatan',
        'last_port': 'Pelabuhan Asal',
        'next_port': 'Pelabuhan Tujuan',
        'notifications': 'Notifikasi',
        'loading_user': 'Memuat data pengguna...',
      },
      'userHistory': {
        'history': 'Riwayat',
        'arrival': 'Kedatangan',
        'departure': 'Keberangkatan',
        'all': 'Semua',
        'empty_title': 'Tidak ada apa-apa. Untuk saat ini.',
        'empty_subtitle': 'Di sinilah Anda akan menemukan\nriwayat pengajuan Anda.',
        'waiting': 'MENUNGGU VERIFIKASI',
        'revision': 'PERLU DIPERBAIKI',
        'approved': 'DITERIMA',
        'declined': 'DITOLAK',
        'arrival_detail': 'Detail Kedatangan',
        'departure_detail': 'Detail Keberangkatan',
        'about': 'Tentang',
        'last_port': 'Pelabuhan Asal',
        'next_port': 'Pelabuhan Tujuan',
        'crewlist': 'Daftar Kru',
        'agent': 'Agen',
        'note_by_officer': 'Catatan dari Petugas',
        'need_fix': 'Perlu Perbaikan',
        'no_notes': 'Tidak ada catatan.',
        'fix_button': 'Perbaiki',
        'done_button': 'Selesai',
        'reports_button': 'Lihat Laporan',
      },
      'userProfile': {
        'profile': 'Profil',
        'settings': 'Pengaturan',
        'notifications': 'Notifikasi',
        'language': 'Bahasa',
        'edit_profile': 'Ubah Profil',
        'select_language': 'Pilih Bahasa',
        'privacy_security': 'Privasi & Keamanan',
        'change_password': 'Ubah Password',
        'logout': 'Keluar',
        'logout_confirm_title': 'Keluar',
        'logout_confirm_body': 'Apakah Anda yakin ingin keluar?',
        'cancel': 'Batal',
      },
      'languageSelection': {
        'title': 'Pilih Bahasa',
      },
      'editAgentProfile': {
        'title': 'Ubah Profil Agen',
        'pick_image_source': 'Pilih Sumber Gambar',
        'gallery': 'Galeri',
        'camera': 'Kamera',
        'change_profile_photo': 'Ubah Foto Profil',
        'full_name': 'Nama Lengkap',
        'full_name_empty': 'Nama tidak boleh kosong',
        'email_address': 'Alamat Email',
        'email_empty': 'Email tidak boleh kosong',
        'email_invalid': 'Format email tidak valid',
        'save_changes': 'Simpan Perubahan',
        'profile_updated': 'Profil berhasil diperbarui!',
      },
      'clearanceForm': {
        'arrival_title': 'Detail Kedatangan',
        'departure_title': 'Detail Keberangkatan',
        'step1': 'Detail',
        'step2': 'Dokumen',
        'step3': 'Kirim',
        'form_instruction': 'Mohon isi informasi sebelum melanjutkan',
        'ship_name': 'Nama Kapal',
        'ship_name_hint': 'Contoh: KM. Bahari Indah',
        'flag': 'Bendera',
        'select_flag': 'Pilih bendera kapal',
        'location': 'Lokasi',
        'select_location': 'Pilih lokasi',
        'last_port': 'Pelabuhan Asal',
        'next_port': 'Pelabuhan Tujuan',
        'eta': 'ETA (Tanggal Tiba)',
        'etd': 'ETD (Tanggal Berangkat)',
        'select_date': 'Pilih Tanggal',
        'wni_crew': 'Kru WNI',
        'wna_crew': 'Kru WNA',
        'required_field': 'Kolom ini harus diisi',
        'next': 'Lanjut',
        'back': 'Kembali',
        'upload_instruction': 'Mohon unggah dokumen yang diperlukan',
        'port_clearance': 'Port Clearance',
        'port_clearance_subtitle': 'Unggah Port Clearance dari pelabuhan sebelumnya',
        'crew_list': 'Daftar Kru',
        'crew_list_subtitle': 'Unggah dokumen daftar kru yang valid',
        'notification_letter': 'Surat Pemberitahuan',
        'notification_letter_subtitle': 'Unggah surat pemberitahuan',
        'choose_file': 'Pilih File',
        'file_uploaded': 'berhasil diunggah',
        'edit': 'Ubah',
        'upload_all_docs': 'Mohon unggah semua dokumen yang diperlukan.',
        'review_confirm': 'Tinjau & Konfirmasi',
        'vessel_details': 'Detail Kapal',
        'crew_count': 'Jumlah Kru',
        'required_docs': 'Dokumen yang Diperlukan',
        'not_uploaded': 'Belum diunggah',
        'submit_application': 'Kirim Pengajuan',
        'submit_dialog_title': 'Kirim',
        'submit_dialog_content': 'Apakah Anda yakin data pengajuan Anda sudah benar? Kirim untuk melanjutkan. Kami akan segera meninjau pengajuan Anda.',
        'cancel': 'Batal',
        'send': 'Kirim',
        'gallery': 'Pilih dari Galeri',
        'camera': 'Ambil Gambar via Kamera',
        'file_picker': 'Pilih dari File',
        'permission_required': 'Izin Diperlukan',
        'camera_permission_message': 'Izin kamera diperlukan untuk mengambil foto. Silakan aktifkan di pengaturan aplikasi.',
        'storage_permission_message': 'Izin penyimpanan diperlukan untuk mengakses foto. Silakan aktifkan di pengaturan aplikasi.',
        'open_settings': 'Buka Pengaturan',
        'arrival_form': 'Form Clearance Kedatangan',
        'departure_form': 'Form Clearance Keberangkatan',
        'saving': 'Mengirim...',
        'success_title': 'Permohonan Dikirim',
        'success_message': 'Permohonan Anda telah berhasil dikirim',
        'error_title': 'Pengiriman Gagal',
        'error_message': 'Gagal mengirim permohonan. Silakan coba lagi.',
        'ok': 'OK',
        'invalid_number': 'Masukkan angka yang valid',
        'select_file_failed': 'Gagal memilih file.',
      },
      'submissionSent': {
        'title': 'Verifikasi Berkas',
        'message': 'Pengajuan Anda sedang diproses. Status akan diperbarui di halaman riwayat setelah diverifikasi oleh petugas.',
        'thank_you': 'Terima kasih atas pengajuan Anda!',
        'submission_received': 'Permohonan Anda telah diterima dan sedang diproses.',
        'tracking_info': 'Anda dapat melacak status permohonan di bagian Riwayat.',
        'back_to_home': 'Kembali ke Beranda',
        'view_history': 'Lihat Riwayat',
      },
      'submissionWaiting': {
        'submission_received': 'Permohonan Diterima',
        'processing': 'Kami sedang memproses permohonan Anda',
        'review_time': 'Tim kami akan meninjau permohonan Anda dalam 1-2 hari kerja.',
        'notification_info': 'Anda akan menerima notifikasi setelah permohonan ditinjau.',
        'check_status': 'Periksa Status',
        'back_to_home': 'Kembali ke Beranda',
        'estimated_time': 'Estimasi waktu pemrosesan: 1-2 hari kerja',
      },
      'clearanceResult': {
        'title': 'Hasil Clearance',
        'print_simulation': 'Mencetak dokumen... (simulasi)',
        'share_simulation': 'Membagikan dokumen... (simulasi)',
        'spb_title': 'Surat Persetujuan Berlayar',
        'immigration_office': 'Kantor Imigrasi Kelas II TPI Sampit',
        'approved_status': 'DISETUJUI',
        'approved_subtitle_arrival': 'Permohonan clearance kedatangan telah disetujui.',
        'approved_subtitle_departure': 'Permohonan clearance keberangkatan telah disetujui.',
        'ship_details': 'Detail Kapal',
        'ship_name': 'Nama Kapal',
        'flag': 'Bendera',
        'agent': 'Agen',
        'voyage_details': 'Detail Pelayaran',
        'last_port': 'Pelabuhan Asal',
        'next_port': 'Pelabuhan Tujuan',
        'eta': 'Tanggal Tiba (ETA)',
        'etd': 'Tanggal Berangkat (ETD)',
        'wni_crew': 'Kru WNI',
        'wna_crew': 'Kru WNA',
        'approved_by': 'Disetujui oleh Petugas Imigrasi:',
        'officer_name': 'Nama Petugas',
        'approval_date': 'Pada tanggal:',
        'close_button': 'Tutup',
      },
      'userNotifications': {
        'title': 'Notifikasi',
        'empty_title': 'Tidak ada apa-apa. Untuk saat ini.',
        'empty_subtitle': 'Di sinilah Anda akan menemukan apa\nyang sedang terjadi',
      },
      'notificationSettings': {
        'title': 'Pengaturan Notifikasi',
        'mute_notifications': 'Bisukan Notifikasi',
        'toggle_sound': 'Suara Notifikasi',
        'view_notifications': 'Lihat Notifikasi',
      },
      //endregion
      
      //region Officer Screens
      'adminHome': {
        'home': 'Beranda',
        'report': 'Laporan',
        'settings': 'Pengaturan',
        'welcome': 'Selamat Datang,',
        'officer': 'Petugas',
        'immigration_office': 'Kantor Imigrasi Kelas II Sampit',
        'arrival_verification': 'Verifikasi Kedatangan',
        'departure_verification': 'Verifikasi Keberangkatan',
        'account_verification': 'Verifikasi Akun',
        'agent_submissions': 'Pemeriksaan Pengajuan Agen',
        'agent_registrations': 'Pemeriksaan Registrasi Agen',
        'email_configuration': 'Konfigurasi Email',
        'manage_email_settings': 'Kelola pengaturan email',
      },
      'adminProfile': {
        'settings': 'Pengaturan',
        'notifications': 'Notifikasi',
        'language': 'Bahasa',
        'english': 'English',
        'indonesian': 'Indonesia',
        'privacy_security': 'Privasi & Keamanan',
        'change_password': 'Ubah Password',
        'logout': 'Keluar',
        'page_not_available': 'halaman belum tersedia.',
        'logout_confirm_title': 'Keluar',
        'logout_confirm_body': 'Apakah Anda yakin ingin keluar?',
        'cancel': 'Batal',
      },
      'verificationList': {
        'arrival_title': 'Verifikasi Kedatangan',
        'departure_title': 'Verifikasi Keberangkatan',
        'reviewed': 'Ditinjau',
        'waiting': 'Menunggu',
        'all': 'Semua',
        'no_data': 'Tidak ada data untuk filter ini.',
        'vessel_name': 'Nama Kapal:',
        'verified': 'DIVERIFIKASI',
        'reviewed_decline': 'DITINJAU - DITOLAK',
        'reviewed_fixing': 'DITINJAU - PERLU PERBAIKAN',
        'review_submission': 'TINJAU PENGAJUAN',
      },
      'accountVerificationList': {
        'title': 'Verifikasi Akun',
        'reviewed': 'Ditinjau',
        'waiting': 'Menunggu',
        'all': 'Semua',
        'no_data': 'Tidak ada data untuk filter ini.',
        'agent_name': 'Nama Agen:',
        'verified': 'DIVERIFIKASI',
        'reviewed_rejected': 'DITINJAU - DITOLAK',
        'review_submission': 'TINJAU PENGAJUAN',
      },
      'accountDetail': {
        'viewing_doc': 'Melihat Dokumen:',
        'simulation_text': 'Ini adalah simulasi melihat file:\n',
        'close': 'Tutup',
        'user_details': 'Detail Pengguna',
        'full_name': 'Nama Lengkap',
        'username': 'Username',
        'email': 'Email',
        'registration_docs': 'Dokumen Registrasi',
        'view_nib': 'Lihat File NIB',
        'view_ktp': 'Lihat File KTP',
        'reject': 'Tolak',
        'verify_account': 'Verifikasi Akun',
        'rejected_message': 'Akun ditolak.',
        'verified_message': 'Akun berhasil diverifikasi.',
      },
      'submissionDetail': {
        'title': 'Detail Verifikasi',
        'submission_info': 'Informasi Pengajuan',
        'ship_name': 'Nama Kapal',
        'flag': 'Bendera',
        'agent_name': 'Nama Agen',
        'location': 'Lokasi',
        'port': 'Pelabuhan',
        'arrival_date': 'Tanggal Kedatangan',
        'departure_date': 'Tanggal Keberangkatan',
        'wni_crew': 'ABK WNI',
        'wna_crew': 'ABK WNA',
        'doc_verification': 'Verifikasi Dokumen',
        'port_clearance': 'Port Clearance',
        'crew_list': 'Daftar Kru',
        'notification_letter': 'Surat Pemberitahuan',
        'action': 'Tindakan',
        'reject_submission': 'Tolak Pengajuan',
        'finish_verification': 'Selesai Verifikasi',
        'check_all_docs_warning': 'Harap periksa semua dokumen terlebih dahulu.',
        'revision_sent_success': 'Status perbaikan telah dikirim ke agen.',
        'approved_success': 'Pengajuan telah disetujui.',
        'rejected_success': 'Pengajuan telah ditolak.',
        'revision_notes_title': 'Catatan Revisi untuk',
        'revision_notes_hint': 'Masukkan catatan perbaikan...',
        'cancel': 'Batal',
        'save': 'Simpan',
        'doc_preview_title': 'Pratinjau Dokumen',
        'doc_preview_content': 'Ini adalah simulasi pratinjau untuk dokumen:\n',
        'close': 'Tutup',
        'status_pending': 'Menunggu',
        'status_approved': 'Disetujui',
        'status_revision': 'Revisi',
        'view': 'Lihat',
        'notes': 'Catatan',
      },
      'officerReport': {
        'title': 'Laporan Petugas',
        'daily_monthly_report': 'Laporan Harian & Bulanan',
        'today': 'Hari Ini',
        'this_month': 'Bulan Ini',
        'arrival': 'Kedatangan',
        'departure': 'Keberangkatan',
        'registration': 'Pendaftaran',
        'daily_report': 'Laporan Harian',
        'create_new_report': 'Buat Laporan Baru',
        'generating_pdf': 'Membuat .pdf',
        'pdf_generation_simulation': 'Membuat laporan PDF... (simulasi)',
        'report_history': 'Riwayat Laporan',
        'created_by': 'Dibuat oleh',
        'see_details': 'LIHAT DETAIL',
        'daily_report_type': 'Laporan Harian',
        'monthly_report_type': 'Laporan Bulanan',
      },
      'editOfficerProfile': {
        'title': 'Ubah Profil',
        'pick_image_source': 'Pilih Sumber Gambar',
        'gallery': 'Galeri',
        'camera': 'Kamera',
        'change_profile_photo': 'Ubah Foto Profil',
        'full_name': 'Nama Lengkap',
        'full_name_empty': 'Nama tidak boleh kosong',
        'email_address': 'Alamat Email',
        'email_empty': 'Email tidak boleh kosong',
        'email_invalid': 'Format email tidak valid',
        'save_changes': 'Simpan Perubahan',
        'profile_updated': 'Profil berhasil diperbarui!',
      },
      'officerNotifications': {
        'title': 'Notifikasi',
        'mark_all_read_tooltip': 'Tandai semua terbaca',
        'mark_all_read_message': 'Semua notifikasi ditandai terbaca (simulasi).',
        'empty_title': 'Tidak ada apa-apa. Untuk saat ini.',
        'empty_subtitle': 'Di sinilah Anda akan menemukan apa\nyang sedang terjadi',
        'new_agent_reg_title': 'Pendaftaran Agen Baru',
        'new_agent_reg_body': 'PT. Bintang Samudera telah mengajukan pendaftaran. Mohon periksa dokumennya.',
        'submission_needs_review_title': 'Pengajuan Perlu Diperiksa',
        'submission_needs_review_body': 'KM. Egon telah mengirimkan pengajuan kedatangan yang perlu Anda periksa.',
        'system_notice_title': 'Pemberitahuan Sistem',
        'system_notice_body': 'Pembaruan sistem terjadwal akan dilakukan malam ini pukul 02:00 WIB.',
      },
      //endregion
    },
  };

  /// Method statis untuk mendapatkan string yang diterjemahkan.
  ///
  /// [context] diperlukan untuk mengakses BuildContext jika diperlukan di masa depan.
  /// [screenKey] adalah kunci unik untuk setiap layar (misal: 'registrationPending').
  /// [stringKey] adalah kunci untuk string spesifik di dalam layar tersebut (misal: 'title').
  /// [langCode] adalah kode bahasa saat ini (misal: 'EN' atau 'ID').
  static String tr({
    required BuildContext context,
    required String screenKey,
    required String stringKey,
    required String langCode,
  }) {
    final code = (langCode).toUpperCase();
    // Primary language
    final primary = _localizedStrings[code]?[screenKey]?[stringKey];
    if (primary != null) return primary;
    // Fallback to English
    final en = _localizedStrings['EN']?[screenKey]?[stringKey];
    if (en != null) return en;
    // Fallback to Indonesian
    final id = _localizedStrings['ID']?[screenKey]?[stringKey];
    if (id != null) return id;
    // Not found
    // TODO: Add missing localization keys
    // For now, return a detailed error message to help with debugging.
    debugPrint('Localization key not found: $screenKey.$stringKey for language $code');
    return '[$screenKey.$stringKey]';
  }
}
